Updating Commvault partner page with updates for 2022E
hpe-storage/scod pull request #162
Opened 2022-11-16 16:56 UTC by denneyliptak

Main change is removing our (now dated) 'Getting Started' steps, as Commvault now has this in their own documentation. I've also updated all links to point to the latest 2022E documentation. Finally, adding a placeholder link for the demo video that will be published soon.

2022-11-16 18:32 UTC, datamattsson requested changes

2022-11-16 18:32 UTC, datamattsson commented on docs/partners/commvault/index.md
> +
I suggest we rethink this. Since we also have a TWP, I suggest we list the assets with their names (better for SEO), something along these lines:

HPE and Commvault collaborate continuously to deliver assets relevant to our joint customers.
- Very Long Name and Link to White Paper (PDF)
- Very Long Name and Link to Video (YouTube)

2022-11-16 18:32 UTC, datamattsson commented on docs/partners/commvault/index.md
> +Check that the [HPE CSI Driver](https://scod.hpedev.io/csi_driver/index.html#compatibility_and_support) and [Commvault software](https://documentation.commvault.com/2022e/essential/124720_system_requ
If this is something we are going to support ongoing I suggest we draw up a table similar to how we do on other partnerships. Not just the current snapshot.

2022-11-16 18:32 UTC, datamattsson commented on docs/partners/commvault/index.md
> +To configure data protection for Kubernetes, follow the [official Commvault documentation](https://documentation.commvault.com/2022e/essential/123634_protecting_kubernetes_with_commvault.html)and ens
There's a space missing after the link closing parenthesis.

2022-11-16 18:32 UTC, datamattsson commented on docs/partners/commvault/index.md
> +## Configure Kubernetes protection with Commvault Backup & Recovery
This header is too long and breaks in my browser.

2022-11-16 18:32 UTC, datamattsson commented on docs/partners/commvault/index.md
> -![](img/commvault1.png)
Delete all the images that are not being referenced any longer.

2022-11-16 18:32 UTC, datamattsson commented on docs/partners/commvault/index.md
> +This guide assumes you have administrative access to Commvault Command Center and access to a Kubernetes cluster with `kubectl` and a `KUBECONFIG` file configured with a cluster administrator account
The use of a KUBECONFIG file is a preference we don't really care about. Please rephrase.

2022-11-16 20:21 UTC, denneyliptak commented on docs/partners/commvault/index.md
> +
I like that. 

I've added this is a 'note' section, does that look ok? Or perhaps there's a better mechanism?
I wanted to provide some separation from the ToC that follows immediatly below.

2022-11-16 20:57 UTC, denneyliptak commented on docs/partners/commvault/index.md
> +Check that the [HPE CSI Driver](https://scod.hpedev.io/csi_driver/index.html#compatibility_and_support) and [Commvault software](https://documentation.commvault.com/2022e/essential/124720_system_requ
Good point; I shouldn't have preserved the 'and later' text from before.
I'll change it to 2022E specifically, as I don't yet know if we'll continually re-evaluate this with each k8s release or each CV release.

2022-11-17 19:52 UTC, datamattsson commented on docs/partners/commvault/index.md
> +
I don't think the "note" looks very good to be honest.

2022-11-17 21:34 UTC, denneyliptak commented on docs/partners/commvault/index.md
> +
Agreed; it's not an ideal use of 'Note'.
[Will this work](https://github.com/hpe-storage/scod/pull/162/commits/ba7d3c2364f6dc83ccfa731549352cde6307db90)?
Then there's a bit of visual separation between the assets and the ToC.

2022-11-18 00:10 UTC, datamattsson commented
LGTM, @c-snell can merge when reviewed and approved. 

One closing comment though, does Commvault have some sort of emblem that our stuff is "certified", similar to what we have on the [OpenShift](https://scod.hpedev.io/partners/redhat_openshift/index.html) page?

2022-11-18 00:10 UTC, datamattsson submitted a review, later dismissed

2022-11-28 22:44 UTC, c-snell approved these changes
lgtm

2022-11-28 22:45 UTC, merged