Cohesity partner addition
hpe-storage/scod pull request #181
Opened 2023-08-15 17:19 UTC by denneyliptak

Greetings Michael,

We just got the predictive URL for the blog and I've added it to the page.
May I request your review of the changes to add the Cohesity 'Partner' page?

The blog goes live on Friday and Parissa has a reference to the SCOD page so we'll want to get it final by then.

Thank you much,
--Denney

2023-08-15 23:43 UTC, datamattsson requested changes
A few nits here and there.

2023-08-15 23:43 UTC, datamattsson commented on docs/partners/cohesity/index.md
> +Hewlett Packard Enterprise and Cohesity offer an integrated approach to solve customer problems commonly found with containerized workloads. HPE Alletra—leveraging the HPE CSI Driver for Kubernetes—t
For readability, add a blank line after headers.

2023-08-15 23:43 UTC, datamattsson commented on docs/partners/cohesity/index.md
> +A Namespace containing a WordPress application will be protected in this example. It contains a variety of Kubernetes resources and objects including:
For readability, add a blank line after headers.

2023-08-15 23:43 UTC, datamattsson commented on docs/partners/cohesity/index.md
> +Review the Cohesity documentation for [Recover Kubernetes Cluster](https://docs.cohesity.com/7_0/Web/UserGuide/Content/Container/ContainerRecover.htm?tocpath=Kubernetes%7C_____5#RecoverKubernetesClus
For readability, add a blank line after headers.

2023-08-15 23:43 UTC, datamattsson commented on docs/partners/cohesity/index.md
> +```text
For readability, add a blank line between paragraphs and markdown elements.

2023-08-15 23:43 UTC, datamattsson commented on docs/partners/cohesity/index.md
> +* Kubernetes `ServiceAccount` with `cluster-admin` persissions.
Speling

2023-08-15 23:43 UTC, datamattsson commented on docs/partners/cohesity/index.md
> +![](img/Cohesity-Recovery-Namespace-locationandrename.png)
Add a line break here, it looks a bit tight in the final rendering.

2023-08-15 23:43 UTC, datamattsson commented on docs/partners/cohesity/index.md
> +![](img/Cohesity_Protection-RunDetails-view.png)
Add a line-break between these.

2023-08-15 23:43 UTC, datamattsson commented on docs/partners/cohesity/index.md
> +![](img/register_k8s.png) <br />
Add a line-break between these.

2023-08-15 23:43 UTC, datamattsson commented on docs/partners/cohesity/index.md
> +External Resources:
External HPE Resources?

2023-08-15 23:43 UTC, datamattsson commented on docs/partners/cohesity/index.md
> +$ diff <(kubectl get all,pvc -n wordpress-orig) <(kubectl get all,pvc -n debug-wordpress-orig)
This `diff` output looks a bit messy. What if we put on block after another instead?

I suspect `diff --side-by-side` will be too wide?

2023-08-15 23:43 UTC, datamattsson commented on docs/partners/cohesity/index.md
> +After the recovery process is complete we can review and compare the associated objects between the two namespaces. In particular, names are similar but discrete volumes, IPs and services exist for e
In general, on SCOD, when we call out Kubernetes resources, we monospace those. So this line would read:

After the recovery process is complete we can review and compare the associated objects between the two `Namespaces`. In particular, names are similar but discrete `PersistentVolumes`, IPs and `Services` exist for each `Namespace`.

2023-08-16 18:08 UTC, denneyliptak commented on docs/partners/cohesity/index.md
> +$ diff <(kubectl get all,pvc -n wordpress-orig) <(kubectl get all,pvc -n debug-wordpress-orig)
Was able to modify the syntax a bit so that mkdocs will help color. This helps improve, yea?

2023-08-16 19:05 UTC, datamattsson requested changes
Can you update `Namespaces` where appropriate?

2023-08-16 20:00 UTC, datamattsson requested changes
Last nit.

2023-08-16 20:00 UTC, datamattsson commented on docs/partners/cohesity/index.md
> +For this example, a WordPress `Namespace` backup will be restored to the source Kubernetes cluster but under a new `Namespace` with a `debug-` prefix (see below). This application can run alongside a
leave "debug-" as-is, that's a name, not a resource kind.

2023-08-16 20:05 UTC, datamattsson approved these changes

2023-08-16 20:05 UTC, merged