Updates for version 1.3.0
hpe-storage/scod pull request #37
Opened 2020-09-02 21:30 UTC by c-snell

Signed-off-by: Chris Snell <snell.chris@gmail.com>

2020-09-02 21:53 UTC, datamattsson requested changes
Please address.

2020-09-02 21:53 UTC, datamattsson commented on docs/csi_driver/deployment.md
> -## Adding additional backends
Changing headers means you need to search and replace references to the header as it can be lurking in other pages. Maybe change to "Adding additional HPE backends" to match previous header.

2020-09-02 21:53 UTC, datamattsson commented on docs/csi_driver/deployment.md
> +## Creating a Secret
We definitely need to revamp this section but I think there's a bit of overlap with https://scod.hpedev.io/csi_driver/deployment.html#add_a_hpe_storage_backend

2020-09-02 21:53 UTC, datamattsson commented on docs/csi_driver/deployment.md
> -
Judging from this section, I don't think you have pulled latest from master before creating this PR?

2020-09-02 22:14 UTC, datamattsson requested changes

2020-09-02 22:14 UTC, datamattsson commented on docs/csi_driver/deployment.md
>  To use the new `Secret` "custom-secret", create a new `StorageClass` using the `Secret` and the necessary `StorageClass` parameters. Please see the requirements section of the respective [CSP](../con
Having both these statements with very similar verbiage doesn't make much sense. Should this be one paragraph?

2020-09-03 01:17 UTC, c-snell commented
resubmitting

2020-09-03 01:17 UTC, closed without merging