Replication-Peer Persistence feature for Primera/3PAR CSP
hpe-storage/scod pull request #39
Opened 2020-09-03 09:35 UTC by sneharai4

2020-09-03 19:36 UTC, c-snell requested changes
Please review suggested changes.

2020-09-03 19:36 UTC, c-snell commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +    • Replication mode is set to sync for peer persistence by default.<br />
```suggestion
    • Currently, the HPE CSI Driver only supports Remote Copy Peer Persistence mode. Async support will be added in a future release.<br />
```

This needs to be moved the beginning of the replication section and highlighted.

Currently, the HPE CSI Driver only supports Remote Copy Peer Persistence mode. Async support will be added in a future release.

2020-09-03 19:36 UTC, c-snell commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +    • Create this custom resource object before creating storage class referring this parameter.<br />
Remove due to being redundant information

```suggestion
```

2020-09-03 19:36 UTC, c-snell commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +
Section needed.

To enable replication within the HPE CSI Driver, the following steps must be completed:
* Create `Secrets` for both primary and target HPE Primera or 3PAR arrays. Refer to [Adding additional backends](https://scod.hpedev.io/csi_driver/deployment.html#adding_additional_backends)
* Create replication custom resource 
* Create replication enabled `StorageClass`

2020-09-03 19:36 UTC, c-snell commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +### Peer Persistence
Keep with official name: Remote Copy with Peer Persistence synchronous replication
```suggestion
### Remote Copy with Peer Persistence synchronous replication
```

2020-09-03 19:36 UTC, c-snell commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +These parameters are applicable only for replication. Both parameters are mandatory. Remote copy group name given in SC if not present will be created.
1. Move the parameters section below to follow order of operation to enable replication.

2. Move this section here to outline the steps that will be followed. 
```
To enable replication within the HPE CSI Driver, the following steps must be completed:

* Create Secrets for both primary and target HPE Primera or 3PAR arrays. Refer to Adding additional backends
* Create replication custom resource
* Create replication enabled StorageClass

For a tutorial on how to enable replication, check out the blog [Enabling Remote Copy using the HPE CSI Driver for Kubernetes on HPE Primera](https://developer.hpe.com/blog/ppPAlQ807Ah8QGMNl1YE/tutorial-enabling-remote-copy-using-the-hpe-csi-driver-for-kubernetes-on)
```

2020-09-03 19:36 UTC, c-snell commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +!!! note
Remove as inserted above.

2020-09-03 19:36 UTC, c-snell commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +This parameter is applicable when user wants to choose specific iSCSI target portal IP on which iSCSI sessions needs to be established.
```suggestion
This parameter allows the ability to specify a subset of HPE Primera/3PAR iSCSI ports for iSCSI sessions. By default, the HPE CSI Driver uses all available iSCSI ports.
```

2020-09-04 05:22 UTC, sneharai4 commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +| remoteCopyGroup <br /> | Text | Name of a new or existing remote copy group on Primera/3PAR array. | **X** | **X** |
Done.

2020-09-04 05:23 UTC, sneharai4 commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +| iscsiPortalIps <br /> | Text <br /> | Comma separated list of target portal IPs. | **X** | **X** |
Done.

2020-09-04 05:24 UTC, sneharai4 commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +These parameters are applicable only for replication. Both parameters are mandatory. Remote copy group name given in SC if not present will be created.
Done.

2020-09-04 05:25 UTC, sneharai4 commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +| remoteCopyGroup    | Text    | Name of a new or existing remote copy group on Primera/3PAR array. |
Done.

2020-09-04 05:25 UTC, sneharai4 commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +| replicationDevices | Text    | Indicates name of custom resource of type `hpereplicationdeviceinfos`. |
Done.

2020-09-04 05:26 UTC, sneharai4 commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +A Custom Resource Definition (CRD) named `hpereplicationdeviceinfos.storage.hpe.com` holds target array details. This object name needs to be used in SC for `replicationDevices`.
Done.

2020-09-04 05:26 UTC, sneharai4 commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +  - targetCpg: FC_r6
Done.

2020-09-04 05:26 UTC, sneharai4 commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +    targetSnapCpg: FC_r6
Done.

2020-09-04 05:29 UTC, sneharai4 commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +    targetName: CSSOS-SSA05
Done.

2020-09-04 05:30 UTC, sneharai4 commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +    targetSecret: secret-r
Done.

2020-09-04 05:32 UTC, sneharai4 commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +    • Create this custom resource object before creating storage class referring this parameter.<br />
Done.

2020-09-04 05:38 UTC, sneharai4 commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +
Done.

2020-09-04 05:40 UTC, sneharai4 commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +### Peer Persistence
Done.

2020-09-04 05:41 UTC, sneharai4 commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +This parameter is applicable when user wants to choose specific iSCSI target portal IP on which iSCSI sessions needs to be established.
Done.

2020-09-04 05:42 UTC, sneharai4 commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +!!! note
Done.

2020-09-04 05:44 UTC, sneharai4 commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +These parameters are applicable only for replication. Both parameters are mandatory. Remote copy group name given in SC if not present will be created.
Done.

2020-09-04 05:44 UTC, sneharai4 commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +    • Replication mode is set to sync for peer persistence by default.<br />
Done.

2020-09-04 05:47 UTC, sneharai4 commented
@c-snell https://developer.hpe.com/blog/ppPAlQ807Ah8QGMNl1YE/tutorial-enabling-remote-copy-using-the-hpe-csi-driver-for-kubernetes-on link is not available.
 It gives a 'Page not found...'

2020-09-04 15:22 UTC, c-snell requested changes

2020-09-04 15:22 UTC, c-snell commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +
Move below CRD example.

2020-09-04 15:22 UTC, c-snell commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +For a tutorial on how to enable replication, check out the blog [Enabling Remote Copy using the HPE CSI Driver for Kubernetes on HPE Primera](https://developer.hpe.com/blog/ppPAlQ807Ah8QGMNl1YE/tutor
This link is to the soon to be release peer persistence blog. The link is valid and will go live on GA date (9/14).

2020-09-07 05:26 UTC, sneharai4 commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +
Done.

2020-09-07 05:26 UTC, sneharai4 commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +For a tutorial on how to enable replication, check out the blog [Enabling Remote Copy using the HPE CSI Driver for Kubernetes on HPE Primera](https://developer.hpe.com/blog/ppPAlQ807Ah8QGMNl1YE/tutor
Okay.

2020-09-07 21:10 UTC, c-snell approved these changes
LGTM

2020-09-07 21:10 UTC, merged