vsphere CSI Driver documentation
hpe-storage/scod pull request #60
Opened 2020-12-02 03:27 UTC by c-snell

2020-12-03 00:08 UTC, datamattsson requested changes
A few nits.

2020-12-03 00:08 UTC, datamattsson commented on docs/partners/vmware/index.md
> +In this example, we will be deploying a stateful MongoDB application with 3 replicas. The persistent volumes deployed by the vSphere CSI Driver will be created using the VM Storage Policy and placed
- VVOL lingo

2020-12-03 00:08 UTC, datamattsson commented on docs/partners/vmware/index.md
> +##### Create a StorageClass
I personally think the `StorageClass` should be part of the deployment process and not the "test & verify" phase of the guide.

2020-12-03 00:08 UTC, datamattsson commented on docs/partners/vmware/index.md
> +kubectl create -f-
This needs to go.

2020-12-03 00:08 UTC, datamattsson commented on docs/partners/vmware/index.md
> +Inspect the `StorageClass` to verify it was created successfully.
I find this a bit redundant, if `kubectl` doesn't return any errors, the resource will be created.

2020-12-03 00:08 UTC, datamattsson commented on docs/partners/vmware/index.md
> +##### Create and Deploy a MongoDB StatefulSet
There's simply too much minutia here, can't we just use a Helm chart to achieve the same thing?

2020-12-03 00:08 UTC, datamattsson commented on docs/partners/vmware/index.md
> +kubectl exec -it mongod-0 -c mongod-container bash
I believe you can exec into sts/mongod and a working Pod will be picked.

2020-12-03 00:08 UTC, datamattsson commented on docs/partners/vmware/index.md
> +Once logged into the instance, type **mongo**.
I also think we should highlight the fact that a persistent volume is attached in the filesystem hierarchy by illustrating it with `df <the path>`.

2020-12-03 00:33 UTC, c-snell commented on docs/partners/vmware/index.md
> +CNS fully supports Storage Policy-Based Management (SPBM) to provision volumes. SPBM is a feature of VMware vSphere that allows an administrator to match VM workload requirements against storage arra
fixed

2020-12-03 00:33 UTC, c-snell commented on docs/partners/vmware/index.md
> +When considering to use block storage within Kubernetes clusters running on VMware, customers need to evaluate which data protocol (FC or iSCSI) is primarily used within their virtualized enviroment.
fixed

2020-12-03 00:40 UTC, c-snell commented on docs/partners/vmware/index.md
> +This guide will cover the configuration and deployment of the vSphere CSI Driver. Cloud Native Storage for vSphere uses the VASA provider and Storage Policy Based Management (SPBM) to create First Cl
yes

2020-12-03 01:34 UTC, c-snell commented on docs/partners/vmware/index.md
> +The following steps are only done on the master node.
This is per their documentation.

2020-12-03 02:14 UTC, c-snell commented on docs/partners/vmware/index.md
> +kubectl describe nodes | egrep "Taints:|Name:"
While the json is possible, I like the simplicity of the original.

2020-12-07 18:33 UTC, datamattsson requested changes
A few more nits and I think we should do one more pass on the install so we're not referencing deprecated bits.

2020-12-07 18:33 UTC, datamattsson commented on docs/partners/vmware/index.md
> +[Deploying a Kubernetes Cluster on vSphere with CSI and CPI](https://cloud-provider-vsphere.sigs.k8s.io/tutorials/kubernetes-on-vsphere-with-kubeadm.html)
Could we add a bullet here to make it a bit more emphasized, like this?

- [Deploying a Kubernetes Cluster on vSphere with CSI and CPI](https://cloud-provider-vsphere.sigs.k8s.io/tutorials/kubernetes-on-vsphere-with-kubeadm.html)

2020-12-07 18:33 UTC, datamattsson commented on docs/partners/vmware/index.md
> +```
This is deprecated according to https://github.com/kubernetes/cloud-provider-vsphere/tree/master/manifests/controller-manager

We should not endorse installing deprecated software, it now points to a single manifest (which makes sense).

2020-12-07 18:33 UTC, datamattsson commented on docs/partners/vmware/index.md
> +The following has been adapted from the vSphere CSI Driver installation guide. Refer to [https://vsphere-csi-driver.sigs.k8s.io/driver-deployment/installation.html](https://vsphere-csi-driver.sigs.k8
Can we make this consistent with #install_the_vsphere_cloud_provider_interface_cpi ? It doesn't matter if use this way of embedding the reference or the former.

2020-12-07 18:33 UTC, datamattsson commented on docs/partners/vmware/index.md
> +password = "VMware1!"
I'm just curious where this password pattern stems from? If this is something we use commonly internally we should not expose it externally.

2020-12-07 18:33 UTC, datamattsson commented on docs/partners/vmware/index.md
> +Create a Kubernetes ``Secret` that will contain the configuration details to connect to your vSphere environment.
A back tick too many in `Secret`

2020-12-07 18:33 UTC, datamattsson commented on docs/partners/vmware/index.md
> +```
Two things, there's a newer version 2.0.1 available. Also can we make this section a tabbed codeblock, one for 6.7U3 and one for 7.0? It seems the CSI driver supports both: https://github.com/kubernetes-sigs/vsphere-csi-driver/tree/master/manifests/v2.0.1

2020-12-07 18:33 UTC, datamattsson commented on docs/partners/vmware/index.md
> +    --set architecture=replicaset,replicaSetName=mongod,replicaCount=3,auth.rootPassword=secretpassword,auth.username=my-user,auth.password=my-password,auth.database=my-database,persistence.storageCl
If we omit the `.persistence` parameters, does it consume the default storageclass correctly? Is there a default size?

I would also break this up for readability:
```markdown
helm install mongodb \
    --set architecture=replicaset \
    --set replicaSetName=mongod \
    --set replicaCount=3 \
etc etc
```

2020-12-07 18:33 UTC, datamattsson commented on docs/partners/vmware/index.md
> +Inspect the pods and PersistentVolumeClaims.
Should we make these fixed width? `Pods` and `PersistentVolumeClaims`?

2020-12-07 18:33 UTC, datamattsson commented on docs/partners/vmware/index.md
> +root@mongod-0:/# df -h
Would you mind just doing `df -h /bitnami/mongodb`?

2020-12-07 18:33 UTC, datamattsson commented on docs/partners/vmware/index.md
> +![Container Volumes](img/container_volumes.png)
This is a great overview screenshot, is possible to try resizing columns and areas to show it a tad bit bigger?

2020-12-07 23:17 UTC, datamattsson requested changes
Moooar nits!

2020-12-07 23:17 UTC, datamattsson commented on docs/partners/vmware/index.md
> +```
I didn't catch this before, but could you just enumerate the `kubectl apply` and skip the output?

2020-12-07 23:17 UTC, datamattsson commented on docs/partners/vmware/index.md
> +kubectl rollout status ds/vsphere-cloud-controller-manager -n kube-system
Duplicate of what is being conveyed above.

2020-12-07 23:17 UTC, datamattsson commented on docs/partners/vmware/index.md
> +Create a Kubernetes ``Secret` that will contain the configuration details to connect to your vSphere environment.
Still two backticks.

2020-12-07 23:17 UTC, datamattsson commented on docs/partners/vmware/index.md
> +```
This looks really messy. Could we summarize, like:

Deploy the necessary RBAC, vSphere CSI Controller `Deployment` and vSphere CSI node `DaemonSet`:

```
One fenced code tab chunk
```

2020-12-07 23:17 UTC, datamattsson commented on docs/partners/vmware/index.md
> +/dev/sdb         49G  374M   47G   1% /bitnami/mongodb
This change has me puzzled, what shows up in the guest OS, a multipath device or a disk?

2020-12-07 23:30 UTC, c-snell commented on docs/partners/vmware/index.md
> +/dev/sdb         49G  374M   47G   1% /bitnami/mongodb
It shows up as a disk rather than a multipath device

2020-12-07 23:34 UTC, datamattsson commented on docs/partners/vmware/index.md
> +/dev/sdb         49G  374M   47G   1% /bitnami/mongodb
but why was it a /dev/mapper path previously?

2020-12-07 23:47 UTC, datamattsson requested changes
Squash one and two more pops up.

2020-12-07 23:47 UTC, datamattsson commented on docs/partners/vmware/index.md
The extra spaces hurts a bit, could we just have the lines one after another?

2020-12-07 23:47 UTC, datamattsson commented on docs/partners/vmware/index.md
> +### Validate the vSphere CSI Driver
If you look at the left menu how this renders, it looks a bit off. Could we just name this section "Validation""?

2020-12-08 01:11 UTC, datamattsson submitted a review, later dismissed
Two more nits then LGTM.

2020-12-08 01:11 UTC, datamattsson commented on docs/partners/index.md
> +* [VMware](vmware/index.html)
index.md

2020-12-08 01:11 UTC, datamattsson commented on docs/partners/vmware/index.md
> +
These lines looks a bit out of place.

2020-12-08 01:19 UTC, merged