1.4.0 updates to 3PAR/Primera and lab guide updates
hpe-storage/scod pull request #67
Opened 2021-01-14 19:11 UTC by c-snell

2021-01-14 20:27 UTC, datamattsson requested changes
A few nits. Did you investigate if we can pull example images (nginx) from quay.io instead of docker.io?

2021-01-14 20:27 UTC, datamattsson commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +| v1.4.0 | iSCSI & FC | - CentOS: 7.6+, 8.1 <br /> - RHEL: 7.6+, 8.1 <br /> - RHCOS | - OpenShift 4.4, 4.6 <br /> - SUSE CaaSP 4.2 | - K8s 1.17-1.20 <br /> - Google Anthos GKE 1.4 | - 3PAR OS: 3.3.1+
This table is a bit of an eye sore. Could this be formatted to with the page estate better. Also:

- SUSE CaaSP 4.2 is listed as a solution but we're missing SLES in the host OS column
- Anthos is listed under "Kubernetes" when it's a partner solution just like OCP and CaaSP
- The leading dashes on the entries just steal horizontal estate

Maybe just merge "Kubernetes" and "Red Hat OpenShift/SUSE CaaSP" to "Platforms" and enumerate them.

2021-01-14 20:27 UTC, datamattsson commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +### VolumeGroupClass QoS parameters
No SnapshotGroupClass parameters?

2021-01-14 20:27 UTC, datamattsson commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +| domain        | Text    | The 3PAR/Primera domain, with which the volume group and related objects are associated with. Example values: "testdomain" |
Not my area of expertise but isn't the customer facing name "virtual domain"? These seemed to be copied verbatim from engineering.

2021-01-14 20:27 UTC, datamattsson commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +| ioMaxLimit        | Text    | I/O-per-second maximum limit. Example values: "10000" |
I/O-per-second is usually abbreviated as IOPS.

2021-01-14 20:27 UTC, datamattsson commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +| latencyGoal        | Text    | Bandwidth maximum limit in kilobytes per second. Example values: "30000" |
parameter name does not match text.

2021-01-14 20:27 UTC, datamattsson commented on docs/learn/persistent_storage/index.md
> +To install the chart with the name `hpe-csi`, add the HPE CSI Driver for Kubernetes helm repo.
Helm is a name.

2021-01-14 20:27 UTC, datamattsson commented on docs/learn/persistent_storage/index.md
> +If all of the components show in Running state, then the HPE CSI driver for Kubernetes and the corresponding Container Storage Providers (CSP) for Nimble, Primera or 3PAR have been successfully deplo
**D**river

2021-01-15 02:53 UTC, c-snell commented on docs/container_storage_provider/hpe_3par_primera/index.md
> +| latencyGoal        | Text    | Bandwidth maximum limit in kilobytes per second. Example values: "30000" |
The parameter and verbage is correct as a volume set must be created and the QoS applied to the vvset. The parameter is then set to the vvset and volumes put into the vvset get the QoS settings applied to them. The parameter name doesn't reflect what is to be named here which has been fixed with Volume Group QoS.

2021-01-15 22:01 UTC, datamattsson requested changes
Mooar nits!

2021-01-15 22:01 UTC, datamattsson commented on docs/learn/persistent_storage/index.md
> +Once everything is removed, **Ctrl+C** to exit and finally you can remove the `namespace`.
When referencing a Kubernetes `kind`, we should use the correct capitalization of the `kind`. Which is `Namespace` in this case.

2021-01-19 18:27 UTC, datamattsson approved these changes
LGTM

2021-01-19 18:28 UTC, merged